'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EasyK.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;scpd
        '''        xmlns=&quot;urn:schemas-upnp-org:service-1-0&quot;&gt;
        '''    &lt;specVersion&gt;
        '''        &lt;major&gt;1&lt;/major&gt;
        '''        &lt;minor&gt;0&lt;/minor&gt;
        '''    &lt;/specVersion&gt;
        '''    &lt;actionList&gt;
        '''        &lt;action&gt;
        '''            &lt;name&gt;GetCurrentTransportActions&lt;/name&gt;
        '''            &lt;argumentList&gt;
        '''                &lt;argument&gt;
        '''                    &lt;name&gt;InstanceID&lt;/name&gt;
        '''                    &lt;direction&gt;in&lt;/direction&gt;
        '''                    &lt;relatedStateVariable&gt;A_ARG_TYPE_InstanceID&lt;/relatedStateVariable&gt;
        '''              [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property AVTransport() As String
            Get
                Return ResourceManager.GetString("AVTransport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;scpd
        '''    xmlns=&quot;urn:schemas-upnp-org:service-1-0&quot;&gt;
        '''    &lt;specVersion&gt;
        '''        &lt;major&gt;1&lt;/major&gt;
        '''        &lt;minor&gt;0&lt;/minor&gt;
        '''    &lt;/specVersion&gt;
        '''    &lt;actionList&gt;
        '''        &lt;action&gt;
        '''            &lt;name&gt;GetCurrentConnectionInfo&lt;/name&gt;
        '''            &lt;argumentList&gt;
        '''                &lt;argument&gt;
        '''                    &lt;name&gt;ConnectionID&lt;/name&gt;
        '''                    &lt;direction&gt;in&lt;/direction&gt;
        '''                    &lt;relatedStateVariable&gt;A_ARG_TYPE_ConnectionID&lt;/relatedStateVariable&gt;
        '''                [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ConnectionManager() As String
            Get
                Return ResourceManager.GetString("ConnectionManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;scpd
        '''    xmlns=&quot;urn:schemas-upnp-org:service-1-0&quot;&gt;
        '''    &lt;specVersion&gt;
        '''        &lt;major&gt;1&lt;/major&gt;
        '''        &lt;minor&gt;0&lt;/minor&gt;
        '''    &lt;/specVersion&gt;
        '''    &lt;actionList&gt;
        '''        &lt;action&gt;
        '''            &lt;name&gt;GetMute&lt;/name&gt;
        '''            &lt;argumentList&gt;
        '''                &lt;argument&gt;
        '''                    &lt;name&gt;InstanceID&lt;/name&gt;
        '''                    &lt;direction&gt;in&lt;/direction&gt;
        '''                    &lt;relatedStateVariable&gt;A_ARG_TYPE_InstanceID&lt;/relatedStateVariable&gt;
        '''                &lt;/argument&gt;
        '''         [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property RenderingControl() As String
            Get
                Return ResourceManager.GetString("RenderingControl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 http-get:*:image/x-ycbcr-yuv420:*,http-get:*:image/x-xpixmap:*,http-get:*:image/x-xfig:*,http-get:*:image/x-xbm:*,http-get:*:image/x-xbitmap:*,http-get:*:image/x-wmf:*,http-get:*:image/x-windows-bmp:*,http-get:*:image/x-rgb:*,http-get:*:image/x-quicktime:*,http-get:*:image/x-psd:*,http-get:*:image/x-portable-pixmap:*,http-get:*:image/x-portable-graymap:*,http-get:*:image/x-portable-bitmap:*,http-get:*:image/x-portable-anymap:*,http-get:*:image/x-png:*,http-get:*:image/x-pict:*,http-get:*:image/x-photoshop:* [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property SinkProtocolInfo() As String
            Get
                Return ResourceManager.GetString("SinkProtocolInfo", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
